name: first workflow
on:
  workflow_dispatch: null
jobs:
  firstjob:
    runs-on: self-hosted
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
  secondjob: null
  runs-on: macos-13
  steps:
    - name: secondJob script
  shell: bash
  run: echo this is the second job echo and this is a multi-line script
